#!/usr/bin/env python3
r"""Figure 3 — incentive response and bounded-rationality fingerprint.

A single, self-contained Nature-style figure that asks how each agent's one-shot
2x2 play relates to incentive sensitivity and revealed behavioural-model structure.
Two panels:

  (a) Action-space quantal curve. Per agent, per-game (delta1c, realized
      canonical-action rate) scatter + a fitted generated-choice logistic response
      curve P(canonical) = Lambda(alpha + lambda * delta1c), with a faded dashed
      soft-token curve overlaid as calibration/readout.
      lambda is the *revealed-choice response precision*: how sharply generated
      actions track the canonical incentive gap. ALL agents (the 4 LLMs + Moore
      et al.) are fit on the SAME q=0.5 belief basis, so the model-vs-human
      lambda is apples-to-apples. The soft-token probability fit is explicitly
      labelled as calibration/readout robustness.

  (b) Bounded-rationality map. Full-sample quantal level-k fits place each agent
      in a reasoning-depth x decision-sharpness plane. Decision sharpness is the
      fitted model's mean modal-action probability, mean_g max(p_g, 1-p_g);
      the raw QLk lambda is retained in the table but not used as the y-axis.
      Per-game model-human alignment is generated by fig1_human_corr.py and
      treated as supplementary.

The supplementary model-selection panel compares L0, NE, QRE, Lk, QLk, CH and
QCH by ten-fold leave-games-out predictive log-loss. Confidence intervals are a
2,000-resample game bootstrap of the stored out-of-fold losses (without refitting
inside each bootstrap sample).

EVERYTHING is fit by binomial MLE on the canonical action axis (docs/METHODS.md HC-2).
For LLMs, the observation unit is the generated/commit decision in each
counterbalance cell. For Moore et al., the headline human lambda is fit on the
individual MGN session choices, matched to the same canonical perspective; no
synthetic human binomial is used.

HONESTY CAVEATS (see the printed NOTE block and inline comments):
  * Ordinal-as-cardinal: the rank-agents feed ordinal payoffs (ranks 1-4) into a
    logit utility. delta1c is on that ordinal scale.
  * Action-space lambda is the panel-a headline; soft token-probability lambda is
    a calibration/readout robustness row. Panel b's sharpness coordinate is a
    probability-scale functional of the fitted QLk policy, not a lambda axis.

Determinism: bootstrap seed 20260520, GroupKFold deterministic (games pre-sorted),
EPS = 1e-6. Reuses the corrected generated/commit decisions and locked estimators.

Run:  .venv/bin/python analysis/layer_a/figscripts/fig3_qre_to_levelk.py
"""
from __future__ import annotations

import math
import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Paths + the locked, validated foundation (import; never reimplement).
# ---------------------------------------------------------------------------

from analysis.layer_a.layer1_lambda_delta1 import fit_lambda, boot_cluster_lambda, EPS  # noqa: E402
from collection.oneshot_common import delta1, delta2, canonical_sign, u_mats  # noqa: E402
from strategic_anatomy import eq_engine as EQ  # noqa: E402
from analysis.probe_common import parse_8vec  # noqa: E402
from analysis.layer_a.levelk_precision_oneshot import build_game_beliefs  # noqa: E402
from analysis.probe_common import game_meta  # noqa: E402
from analysis.layer_a.build_regime_rationality import build_game_panel  # noqa: E402
from analysis.layer_a.src import human_lambda_mgn as HL  # noqa: E402

from scipy.optimize import minimize  # noqa: E402
from scipy.special import expit, logsumexp  # noqa: E402
from scipy.stats import pearsonr, spearmanr  # noqa: E402
from sklearn.model_selection import GroupKFold  # noqa: E402
from strategic_anatomy.config import human_refs_root, repo_root, results_root, taxonomy_dir

ROOT = repo_root()


MASTER = taxonomy_dir() / "human_game_master_per_canonical.csv"
UNIFIED = human_refs_root() / "unified_pairs.parquet"
FIG_DIR = ROOT / "analysis" / "layer_a" / "figures"
TAB_DIR = results_root() / "layer_a"
FIG_DIR.mkdir(parents=True, exist_ok=True)
TAB_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Frozen presentation (must match Figs 1-2; confirmed against
# analysis/block_a/make_rationality_figure.py COLOR).
# ---------------------------------------------------------------------------
LLMS = ["qwen", "qwen_instruct", "llama31_instruct", "gptoss"]
AGENTS = LLMS + ["nagel"]            # Nagel is the 5th (human) agent
COLOR = {
    "qwen": "#1f77b4", "qwen_instruct": "#17becf",
    "llama31_instruct": "#2ca02c", "gptoss": "#9467bd",
    "nagel": "#c83b31",
}
DISPLAY = {
    "qwen": "Qwen2.5", "qwen_instruct": "Qwen2.5-I",
    "llama31_instruct": "Llama", "gptoss": "GPT-OSS",
    "nagel": "Moore et al.",
}

# behavioural model classes (left->right = increasing structure)
MODEL_ORDER = ["L0", "NE", "QRE", "Lk", "QLk", "CH", "QCH"]
N_PARAMS = {"L0": 0, "NE": 0, "QRE": 1, "Lk": 2, "QLk": 4, "CH": 1, "QCH": 2}

SEED = 20260520
N_BOOT = 2000
N_BOOT_FINGERPRINT = 500
LOG2 = float(np.log(2.0))
NE_TREMBLE = 0.02                    # fixed trembling-hand floor for the NE model
LEVELS = ["L1", "L2", "L3"]         # the level mixture used by Lk / QLk
CH_KMAX = 4                          # CH/QCH Poisson level support k = 0..4


# ===========================================================================
#  Data assembly: per-agent, per-game (s_g, n_g, pref_canon, delta1c, beliefs)
# ===========================================================================
def _clip(p):
    return np.clip(p, EPS, 1.0 - EPS)


def _action_to_act0prob(a) -> float:
    """0 -> 1.0 (opponent surely plays act0); 1 -> 0.0; anything else -> 0.5."""
    try:
        a = int(a)
    except (TypeError, ValueError):
        return 0.5
    if a == 0:
        return 1.0
    if a == 1:
        return 0.0
    return 0.5


def _flip_to_canonical(p_act0: float, canon: int) -> float:
    """Convert a positional P(P1 plays act0) to P(P1 plays the canonical action)."""
    return p_act0 if int(canon) == 0 else 1.0 - p_act0


def build_agent_games() -> dict[str, pd.DataFrame]:
    """One tidy per-game frame per agent.

    Columns (every agent): game_code, s, n, pbar (soft target on canonical axis),
    delta1c (canonical-signed L1 gap at q=0.5), complexity_score, vec8 (list),
    canon (int), q2 (=0.5 for the headline basis), plus the precomputed per-game
    level belief gaps gap_L1/gap_L2/gap_L3 and the diagnostic flag. Behaviour comes
    from the corrected generated/commit panel, never from the stale 06-13 cache.
    """
    panel, _ = build_game_panel()
    master = pd.read_csv(MASTER)[[
        "game_code", "canonical_8vec", "canonical_action_p1",
        "delta1_canonical", "complexity_score", "nagel_pcanon", "nagel_lk_type",
    ]].copy()
    meta = game_meta()
    qhat_dummy = pd.Series(0.5, index=meta["game_code"])
    beliefs = build_game_beliefs(meta, qhat_dummy)  # gap_L1/L2/L3 + diagnostic (model-free)
    belief_cols = ["game_code", "gap_L1", "gap_L2", "gap_L3", "diagnostic"]
    beliefs = beliefs[belief_cols]

    out: dict[str, pd.DataFrame] = {}

    # ---- the four LLMs ----
    for m in LLMS:
        d = panel[panel["agent"].eq(m)].copy()
        d = d.merge(master[["game_code", "delta1_canonical", "complexity_score"]],
                    on="game_code", how="left")
        d = d.sort_values("game_code").reset_index(drop=True)
        p_canon = np.where(
            d["canonical_action_p1"].astype(int).eq(0),
            d["realized_p1"].to_numpy(float),
            1.0 - d["realized_p1"].to_numpy(float),
        )
        p_soft = np.where(
            d["canonical_action_p1"].astype(int).eq(0),
            d["pref0_p1"].to_numpy(float),
            1.0 - d["pref0_p1"].to_numpy(float),
        )
        if "n_p1" not in d.columns:
            raise AssertionError(f"{m}: missing n_p1; refusing to fabricate Fig 3 cell counts")
        n_series = pd.to_numeric(d["n_p1"], errors="coerce")
        bad_n = n_series.isna() | (n_series <= 0) | (np.abs(n_series - np.rint(n_series)) > 1e-9)
        if bad_n.any():
            examples = d.loc[bad_n, ["game_code", "n_p1"]].head(8).to_dict("records")
            raise AssertionError(f"{m}: invalid n_p1 values in Fig 3 source panel: {examples}")
        n = n_series.astype(int).to_numpy()
        if not np.all(n == 4):
            vals = sorted(pd.Series(n).value_counts().to_dict().items())
            raise AssertionError(
                f"{m}: expected exactly 4 corrected-root P1 baseline cells per game; got {vals}"
            )
        s_float = p_canon * n
        if not np.allclose(s_float, np.rint(s_float), atol=1e-6):
            bad = d.loc[
                ~np.isclose(s_float, np.rint(s_float), atol=1e-6),
                ["game_code", "realized_p1", "n_p1"],
            ]
            raise AssertionError(f"{m}: p_canon*n_p1 is not integral for {bad.head(8).to_dict('records')}")
        rec = pd.DataFrame({
            "game_code": d["game_code"].to_numpy(),
            "family": d["family"].to_numpy(),
            "s": np.rint(s_float).astype(int),
            "n": n,
            "pbar": p_soft,
            "p_action": p_canon,
            "delta1c": d["delta1_canonical"].to_numpy(float),
            "delta1c_unif": d["delta1_canonical"].to_numpy(float),
            "complexity_score": d["complexity_score"].to_numpy(float),
            "canon": d["canonical_action_p1"].astype(int).to_numpy(),
            "vec8_str": d["vec8"].to_numpy(),
            "q2": np.full(len(d), 0.5),
        })
        rec = rec.merge(beliefs, on="game_code", how="left")
        rec["vec8"] = [parse_8vec(s) for s in rec["vec8_str"]]
        out[m] = rec

    # ---- Moore et al. (human) — real individual choices, not synthetic counts ----
    human_ind = HL.individual_choices()
    human_counts = (human_ind.groupby("game_code")
                    .agg(s=("y_canon", "sum"),
                         n=("y_canon", "size"),
                         p_action=("y_canon", "mean"))
                    .reset_index())
    nag = master[["game_code", "canonical_8vec", "canonical_action_p1",
                  "nagel_pcanon", "nagel_lk_type"]].copy()
    nag = nag.dropna(subset=["nagel_pcanon"]).sort_values("game_code").reset_index(drop=True)
    nag = nag.merge(human_counts, on="game_code", how="inner")
    max_err = float((nag["p_action"] - nag["nagel_pcanon"]).abs().max())
    assert max_err < 1e-9, f"individual MGN p(canonical) != master aggregate (max {max_err:.2e})"
    nag["vec8"] = [parse_8vec(s) for s in nag["canonical_8vec"]]
    nag["canon"] = nag["canonical_action_p1"].astype(int)
    nag = nag.merge(master[["game_code", "delta1_canonical", "complexity_score"]],
                    on="game_code", how="left")
    nag["delta1c"] = nag["delta1_canonical"].astype(float)
    nag["delta1c_unif"] = nag["delta1c"]
    nag["q2"] = 0.5
    nag["family"] = nag["nagel_lk_type"]
    nag["pbar"] = nag["p_action"].astype(float)
    nag["s"] = nag["s"].astype(int)
    nag["n"] = nag["n"].astype(int)
    nag = nag.merge(beliefs, on="game_code", how="left")
    out["nagel"] = nag[["game_code", "family", "s", "n", "pbar", "delta1c", "delta1c_unif",
                        "complexity_score", "p_action", "canon", "vec8", "q2",
                        "gap_L1", "gap_L2", "gap_L3", "diagnostic"]].reset_index(drop=True)
    print("  [source] behaviour = corrected generated moves / GPT-OSS commit, not stale cache")
    print("  [source] human λ/counts = individual MGN decisions")
    return out


# ===========================================================================
#  Per-game theoretical predictions (model-independent geometry)
# ===========================================================================
def _ne_p1_act0(vec8) -> float:
    """P1 act0-probability under the standard NE selection.

    unique pure -> 0/1; unique mixed -> interior; 2-pure+mixed -> risk-dominant
    (fallback payoff-dominant -> mixed coordinate -> 0.5). Always returns a finite
    probability in [0,1]; the trembling-hand floor is applied by the caller.
    """
    p1, p2 = EQ.matrices_from_8vec(vec8)
    pairs, kind = EQ.enumerate_nash(p1, p2)
    if not pairs:
        return 0.5
    pure = [pr for pr in pairs if pr[0] in (0.0, 1.0) and pr[1] in (0.0, 1.0)]
    mixed = [pr for pr in pairs if pr not in pure]
    if len(pairs) == 1:
        return float(pairs[0][0])
    # multiple equilibria: try risk-dominant, then payoff-dominant, then mixed, then 0.5
    pne = EQ.pure_nash_equilibria(p1, p2)
    rd = EQ.risk_dominant_ne(pne, p1, p2)
    if rd is not None:
        return float(_action_to_act0prob(rd[0]) if rd[0] in (0, 1) else rd[0])
    pd_ne = EQ.payoff_dominant_ne(pne, p1, p2)
    if pd_ne is not None:
        return float(_action_to_act0prob(pd_ne[0]) if pd_ne[0] in (0, 1) else pd_ne[0])
    if mixed:
        return float(mixed[0][0])
    return 0.5


def ne_pred(df: pd.DataFrame) -> np.ndarray:
    """NE prediction on the CANONICAL axis, made finite with a fixed tremble."""
    out = np.empty(len(df))
    for i, (vec, canon) in enumerate(zip(df["vec8"], df["canon"])):
        p_act0 = _ne_p1_act0(vec)
        p_can = _flip_to_canonical(p_act0, int(canon))
        out[i] = (1.0 - 2.0 * NE_TREMBLE) * p_can + NE_TREMBLE
    return _clip(out)


# ---------------------------------------------------------------------------
# Vectorized payoff geometry. ``delta1``/``delta2`` (from oneshot_common) are the
# single source of truth for the scalar incentive gaps; here we vectorize the SAME
# algebra over a whole stack of games so the QRE/CH fixed points (called thousands
# of times inside the optimizer + bootstrap) never re-parse a vector per iteration.
# A 256-entry cache keyed on the frame's vec8-list object identity avoids rebuilding
# the stack on every predict() call. The vectorized gaps are asserted equal to the
# scalar delta1/delta2 in __main__ (see _selfcheck_vectorization).
# ---------------------------------------------------------------------------
_STACK_CACHE: dict[int, tuple] = {}


def _payoff_stack(df: pd.DataFrame) -> tuple:
    """Return (U1, U2, canon) with U1,U2 shape (G,2,2) for the frame's vec8 column.

    U1[g,i,j] = P1 payoff (row i, col j); U2 likewise. delta1(vec,q) ==
    q*U1[:,0,0]+(1-q)*U1[:,0,1] - (q*U1[:,1,0]+(1-q)*U1[:,1,1]); delta2(vec,q) ==
    q*U2[:,0,0]+(1-q)*U2[:,1,0] - (q*U2[:,0,1]+(1-q)*U2[:,1,1]).
    """
    key = id(df["vec8"].values)
    hit = _STACK_CACHE.get(key)
    if hit is not None and hit[0].shape[0] == len(df):
        return hit
    V = np.asarray([list(v) for v in df["vec8"]], dtype=float)   # (G,8)
    U1 = V[:, :4].reshape(-1, 2, 2)
    U2 = V[:, 4:].reshape(-1, 2, 2)
    canon = df["canon"].to_numpy(int)
    res = (U1, U2, canon)
    if len(_STACK_CACHE) > 256:
        _STACK_CACHE.clear()
    _STACK_CACHE[key] = res
    return res


def _vdelta1(U1: np.ndarray, q: np.ndarray) -> np.ndarray:
    """Vectorized EU1(act0)-EU1(act1) over a stack; q is a length-G array."""
    return (q * U1[:, 0, 0] + (1 - q) * U1[:, 0, 1]
            - (q * U1[:, 1, 0] + (1 - q) * U1[:, 1, 1]))


def _vdelta2(U2: np.ndarray, q: np.ndarray) -> np.ndarray:
    """Vectorized EU2(act0)-EU2(act1) over a stack; q is a length-G array."""
    return (q * U2[:, 0, 0] + (1 - q) * U2[:, 1, 0]
            - (q * U2[:, 0, 1] + (1 - q) * U2[:, 1, 1]))


def qre_pred(df: pd.DataFrame, lam: float, n_iter: int = 200, damp: float = 0.5,
             tol: float = 1e-9) -> np.ndarray:
    """QRE prediction on the canonical axis (vectorized fixed point over all games)."""
    U1, U2, canon = _payoff_stack(df)
    G = U1.shape[0]
    s1 = np.full(G, 0.5)
    s2 = np.full(G, 0.5)
    for _ in range(n_iter):
        n1 = expit(lam * _vdelta1(U1, s2))
        n2 = expit(lam * _vdelta2(U2, s1))
        ns1 = (1 - damp) * s1 + damp * n1
        ns2 = (1 - damp) * s2 + damp * n2
        if np.max(np.abs(ns1 - s1)) < tol and np.max(np.abs(ns2 - s2)) < tol:
            s1, s2 = ns1, ns2
            break
        s1, s2 = ns1, ns2
    p_can = np.where(canon == 0, s1, 1.0 - s1)
    return _clip(p_can)


def ch_pred(df: pd.DataFrame, tau: float, lam: float | None,
            kmax: int = CH_KMAX) -> np.ndarray:
    """Cognitive-hierarchy prediction on the canonical axis (vectorized over games).

    Levels k=0..kmax with Poisson weights pi_k ~ e^{-tau} tau^k / k!. Level k (>=1)
    responds to the NORMALIZED mixture of all lower levels 0..k-1. P1 and P2 ladders
    advance in lockstep. lam is None -> sharp best response (CH); else quantal at lam
    (QCH). Returns P1's act0-prob under the Poisson-weighted mixture, flipped to the
    canonical axis.
    """
    U1, U2, canon = _payoff_stack(df)
    G = U1.shape[0]
    w = _poisson_weights(tau, kmax)                  # (kmax+1,)
    a1 = np.empty((kmax + 1, G))
    a2 = np.empty((kmax + 1, G))
    a1[0] = 0.5
    a2[0] = 0.5
    for k in range(1, kmax + 1):
        wl = w[:k]
        wl = wl / wl.sum() if wl.sum() > 0 else np.full(k, 1.0 / k)
        q_for_p1 = wl @ a2[:k]                        # belief about P2 act0  (G,)
        q_for_p2 = wl @ a1[:k]                        # belief about P1 act0  (G,)
        d1 = _vdelta1(U1, q_for_p1)
        d2 = _vdelta2(U2, q_for_p2)
        if lam is None:
            a1[k] = np.where(d1 > 0, 1.0, np.where(d1 < 0, 0.0, 0.5))
            a2[k] = np.where(d2 > 0, 1.0, np.where(d2 < 0, 0.0, 0.5))
        else:
            a1[k] = expit(lam * d1)
            a2[k] = expit(lam * d2)
    p_act0 = w @ a1                                   # (G,)
    p_can = np.where(canon == 0, p_act0, 1.0 - p_act0)
    return _clip(p_can)


def _poisson_weights(tau: float, kmax: int = CH_KMAX) -> np.ndarray:
    ks = np.arange(kmax + 1)
    fact = np.array([math.factorial(int(k)) for k in ks], dtype=float)
    with np.errstate(over="ignore"):
        w = np.exp(-tau) * np.power(float(tau), ks) / fact
    tot = w.sum()
    return w / tot if tot > 0 else np.full(kmax + 1, 1.0 / (kmax + 1))


def _gap_sharp(gap: float) -> float:
    """Sharp best-response indicator on a canonical-signed gap (0.5 on exact tie)."""
    if gap > 0:
        return 1.0
    if gap < 0:
        return 0.0
    return 0.5


def lk_pred(df: pd.DataFrame, pi: np.ndarray) -> np.ndarray:
    """Level-k mixture (sharp best responses), pi over {L1,L2,L3}. Canonical axis.

    gap_Lk are already canonical-signed (positive favours the canonical action), so
    P_k^sharp = 1[gap_k>0] is already on the canonical axis -- no flip needed.
    """
    P = np.zeros(len(df))
    for w, b in zip(pi, LEVELS):
        g = df[f"gap_{b}"].to_numpy(float)
        Pk = np.where(g > 0, 1.0, np.where(g < 0, 0.0, 0.5))
        P += w * Pk
    return _clip(P)


def qlk_pred(df: pd.DataFrame, pi4: np.ndarray, lam: float) -> np.ndarray:
    """Quantal level-k: pi over {L0,L1,L2,L3}, shared precision lambda. Canonical axis.

    pi0 * 0.5 + sum_{k in L1,L2,L3} pi_k * Lambda(lam * gap_k).
    """
    P = pi4[0] * 0.5
    for w, b in zip(pi4[1:], LEVELS):
        P = P + w * expit(lam * df[f"gap_{b}"].to_numpy(float))
    return _clip(P)


# ===========================================================================
#  Binomial MLE fitting (shared core + per-model parameterizations)
# ===========================================================================
def _nll(p: np.ndarray, s: np.ndarray, n: np.ndarray) -> float:
    p = _clip(p)
    return float(-np.sum(s * np.log(p) + (n - s) * np.log(1.0 - p)))


def _softmax_simplex(theta: np.ndarray) -> np.ndarray:
    """Map free params (len k-1) to a length-k simplex via softmax with an anchor 0."""
    z = np.concatenate([[0.0], theta])
    z = z - z.max()
    e = np.exp(z)
    return e / e.sum()


def _fit_restarts(fun, x0_list, bounds=None):
    """L-BFGS-B with several restarts; return best (x, fun)."""
    best_x, best_f = None, np.inf
    for x0 in x0_list:
        try:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                r = minimize(fun, np.asarray(x0, float), method="L-BFGS-B",
                             bounds=bounds, options={"maxiter": 500})
            if np.isfinite(r.fun) and r.fun < best_f:
                best_f, best_x = float(r.fun), np.asarray(r.x, float)
        except Exception:
            continue
    return best_x, best_f


def fit_model(name: str, df: pd.DataFrame) -> dict:
    """Fit one behavioural model by binomial MLE on df. Returns a param dict with a
    ``predict`` closure (callable on any frame with the same geometry columns)."""
    s = df["s"].to_numpy(float)
    n = df["n"].to_numpy(float)
    rng = np.random.default_rng(SEED)

    if name == "L0":
        return {"name": name, "params": {}, "predict": lambda d: _clip(np.full(len(d), 0.5))}

    if name == "NE":
        return {"name": name, "params": {}, "predict": ne_pred}

    if name == "QRE":
        def f(th):
            lam = th[0]
            return _nll(qre_pred(df, lam), s, n)
        x, _ = _fit_restarts(f, [[0.5], [0.1], [1.0], [2.0]], bounds=[(0.0, 50.0)])
        lam = float(x[0]) if x is not None else np.nan
        return {"name": name, "params": {"lambda": lam},
                "predict": lambda d, lam=lam: qre_pred(d, lam)}

    if name == "Lk":
        def f(th):
            pi = _softmax_simplex(th)            # 2 free -> 3-simplex over L1,L2,L3
            return _nll(lk_pred(df, pi), s, n)
        starts = [[0.0, 0.0]] + [list(v) for v in rng.normal(0, 1.0, size=(4, 2))]
        x, _ = _fit_restarts(f, starts)
        pi = _softmax_simplex(x) if x is not None else np.full(3, 1 / 3)
        return {"name": name, "params": {"pi_L1": pi[0], "pi_L2": pi[1], "pi_L3": pi[2]},
                "predict": lambda d, pi=pi: lk_pred(d, pi)}

    if name == "QLk":
        def f(th):
            pi = _softmax_simplex(th[:3])        # 3 free -> 4-simplex over L0,L1,L2,L3
            lam = th[3]
            return _nll(qlk_pred(df, pi, lam), s, n)
        starts = ([[0, 0, 0, 0.5], [0, 0, 0, 1.0], [0, 0, 0, 0.1]]
                  + [list(v) + [abs(g)] for v, g in
                     zip(rng.normal(0, 1.0, size=(4, 3)), rng.uniform(0.1, 2.0, 4))])
        x, _ = _fit_restarts(
            f, starts, bounds=[(-8, 8), (-8, 8), (-8, 8), (0.0, 50.0)])
        if x is not None:
            pi = _softmax_simplex(x[:3]); lam = float(x[3])
        else:
            pi = np.full(4, 0.25); lam = np.nan
        return {"name": name,
                "params": {"pi_L0": pi[0], "pi_L1": pi[1], "pi_L2": pi[2],
                           "pi_L3": pi[3], "lambda": lam},
                "predict": lambda d, pi=pi, lam=lam: qlk_pred(d, pi, lam)}

    if name == "CH":
        def f(th):
            return _nll(ch_pred(df, th[0], None), s, n)
        x, _ = _fit_restarts(f, [[1.0], [0.5], [1.5], [2.5]], bounds=[(0.0, 10.0)])
        tau = float(x[0]) if x is not None else np.nan
        return {"name": name, "params": {"tau": tau},
                "predict": lambda d, tau=tau: ch_pred(d, tau, None)}

    if name == "QCH":
        def f(th):
            tau, lam = th
            return _nll(ch_pred(df, tau, lam), s, n)
        starts = [[1.0, 0.5], [0.5, 1.0], [1.5, 0.2], [2.0, 1.0], [0.8, 2.0]]
        x, _ = _fit_restarts(f, starts, bounds=[(0.0, 10.0), (0.0, 50.0)])
        if x is not None:
            tau, lam = float(x[0]), float(x[1])
        else:
            tau = lam = np.nan
        return {"name": name, "params": {"tau": tau, "lambda": lam},
                "predict": lambda d, tau=tau, lam=lam: ch_pred(d, tau, lam)}

    raise ValueError(name)


# ===========================================================================
#  Panel (b): leave-GAMES-out CV predictive log-loss
# ===========================================================================
def cv_logloss(df: pd.DataFrame) -> dict[str, np.ndarray]:
    """Per model: per-game out-of-fold log-loss array (len = n_games), aligned to a
    pre-sorted game order so bootstrap resampling is deterministic.

    L0 and NE are parameter-free, so their OOF prediction equals their in-sample
    prediction (no fitting); we still pass each game through the standard binomial
    log-loss for a comparable bar.
    """
    df = df.sort_values("game_code").reset_index(drop=True)
    games = df["game_code"].to_numpy()
    gkf = GroupKFold(n_splits=min(10, df["game_code"].nunique()))
    ll = {m: np.full(len(df), np.nan) for m in MODEL_ORDER}

    for tr_idx, te_idx in gkf.split(df, groups=games):
        tr = df.iloc[tr_idx]
        te = df.iloc[te_idx]
        s_te = te["s"].to_numpy(float)
        n_te = te["n"].to_numpy(float)
        for m in MODEL_ORDER:
            fit = fit_model(m, tr)
            p = fit["predict"](te)
            p = _clip(p)
            # per-game normalized log-loss: -[s log p + (n-s) log(1-p)] / n
            ll[m][te_idx] = -(s_te * np.log(p) + (n_te - s_te) * np.log(1.0 - p)) / n_te
    return ll


def boot_logloss_ci(ll_arr: np.ndarray, n_boot: int = N_BOOT, seed: int = SEED):
    """Bootstrap-by-game CI on the mean of stored per-game OOF log-loss (no refit)."""
    v = ll_arr[np.isfinite(ll_arr)]
    if v.size == 0:
        return np.nan, np.nan, np.nan
    rng = np.random.default_rng(seed)
    means = v[rng.integers(0, v.size, size=(n_boot, v.size))].mean(1)
    return float(v.mean()), float(np.percentile(means, 2.5)), float(np.percentile(means, 97.5))


def build_model_selection_cv(
    agent_games: dict[str, pd.DataFrame],
) -> tuple[pd.DataFrame, dict[str, dict[str, tuple[float, float, float]]]]:
    """Run the canonical leave-games-out comparison and persist its estimands.

    Models are refit within each of ten ``GroupKFold`` training partitions, with
    ``game_code`` as the held-out group.  The interval is a percentile bootstrap
    over the 144 stored out-of-fold per-game log losses; models are not refit
    inside that descriptive game-composition bootstrap.
    """
    rows = []
    cv_full: dict[str, dict[str, tuple[float, float, float]]] = {}
    for agent in AGENTS:
        d = agent_games[agent]
        losses = cv_logloss(d)
        n_games = int(d["game_code"].nunique())
        n_splits = min(10, n_games)
        cv_full[agent] = {}
        for model in MODEL_ORDER:
            mean, lo, hi = boot_logloss_ci(losses[model])
            cv_full[agent][model] = (mean, lo, hi)
            rows.append({
                "agent": agent,
                "display": DISPLAY[agent],
                "model": model,
                "n_params": N_PARAMS[model],
                "mean_logloss": mean,
                "ci_lo": lo,
                "ci_hi": hi,
                "n_games": n_games,
                "n_observations": int(d["n"].sum()),
                "n_splits": n_splits,
                "cv_group": "game_code",
                "ci_method": (
                    f"percentile bootstrap of stored OOF per-game losses; "
                    f"n_boot={N_BOOT}; no bootstrap refit"
                ),
            })
        best = min(MODEL_ORDER, key=lambda model: cv_full[agent][model][0])
        summary = " ".join(
            f"{model}={cv_full[agent][model][0]:.3f}" for model in MODEL_ORDER
        )
        print(f"  [{agent:18s}] best={best:3s} | {summary}")

    table = pd.DataFrame(rows)
    table.to_csv(TAB_DIR / "f3_model_selection_cv.csv", index=False)
    return table, cv_full


# ===========================================================================
#  Fingerprint helpers (depth + precision, with bootstrap)
# ===========================================================================
def qlk_depth(params: dict) -> float:
    """QLk mean reasoning level Sum_k k * pi_k over k = 0..3."""
    pis = [params.get(f"pi_L{k}", np.nan) for k in range(4)]
    if any(np.isnan(p) for p in pis):
        return np.nan
    return float(sum(k * p for k, p in enumerate(pis)))


def fit_fingerprint(df: pd.DataFrame) -> dict:
    """Full-sample QLk + CH + QCH fits -> depth/precision fingerprint for one agent."""
    qlk = fit_model("QLk", df)["params"]
    ch = fit_model("CH", df)["params"]
    qch = fit_model("QCH", df)["params"]
    return {
        "tau_CH": ch.get("tau", np.nan),
        "tau_QCH": qch.get("tau", np.nan),
        "lambda_QCH": qch.get("lambda", np.nan),
        "depth_pi": qlk_depth(qlk),
        "lambda_QLk": qlk.get("lambda", np.nan),
        "pi_L0": qlk.get("pi_L0", np.nan), "pi_L1": qlk.get("pi_L1", np.nan),
        "pi_L2": qlk.get("pi_L2", np.nan), "pi_L3": qlk.get("pi_L3", np.nan),
    }


def boot_fingerprint(df: pd.DataFrame, n_boot: int = N_BOOT_FINGERPRINT, seed: int = SEED):
    """Bootstrap-by-game CI on (depth_pi, lambda_QLk, tau_QCH) by refitting on
    resampled games. Returns dict of (lo, hi) per quantity."""
    df = df.reset_index(drop=True)
    games = df["game_code"].unique()
    idx_by_g = {g: np.where(df["game_code"].to_numpy() == g)[0] for g in games}
    rng = np.random.default_rng(seed + 7)
    depth, lam, tau = [], [], []
    for _ in range(n_boot):
        pick = rng.choice(games, size=len(games), replace=True)
        ii = np.concatenate([idx_by_g[g] for g in pick])
        sub = df.iloc[ii].reset_index(drop=True)
        try:
            qlk = fit_model("QLk", sub)["params"]
            qch = fit_model("QCH", sub)["params"]
            d = qlk_depth(qlk)
            if np.isfinite(d):
                depth.append(d)
            if np.isfinite(qlk.get("lambda", np.nan)):
                lam.append(qlk["lambda"])
            if np.isfinite(qch.get("tau", np.nan)):
                tau.append(qch["tau"])
        except Exception:
            continue

    def _ci(a):
        a = np.asarray(a, float)
        return (float(np.percentile(a, 2.5)), float(np.percentile(a, 97.5))) if a.size else (np.nan, np.nan)

    return {"depth_pi": _ci(depth), "lambda_QLk": _ci(lam), "tau_QCH": _ci(tau)}


# ===========================================================================
#  Griffiths cardinal axis (SEPARATE robustness; never on the rank lambda bar)
# ===========================================================================
def griffiths_cardinal_lambda() -> pd.DataFrame:
    """Soft lambda for Griffiths on its OWN cardinal payoff axis.

    Rank-clean Griffiths subset from unified_pairs (sample=='griffiths'). The
    incentive gap is delta1c on the CARDINAL matrix (matrix_8vec) at q=0.5, oriented
    to the canonical action. This is a SEPARATE-AXIS robustness object: it must never
    be plotted on the same lambda bar as the ordinal rank agents.
    """
    up = pd.read_parquet(UNIFIED)
    up = up.loc[:, ~up.columns.duplicated()]
    g = up[up["sample"] == "griffiths"].copy()
    if g.empty:
        return pd.DataFrame([{"agent": "griffiths", "axis": "cardinal",
                              "lam_soft": np.nan, "ci_lo": np.nan, "ci_hi": np.nan,
                              "n_games": 0, "note": "no griffiths rows"}])

    def _vec(x):
        import json
        return [float(v) for v in (json.loads(x) if isinstance(x, str) else list(x))]

    g["vec8"] = [_vec(v) for v in g["matrix_8vec"]]
    g["canon"] = g["canonical_action_p1"].astype(int)
    g["delta1c"] = [canonical_sign(delta1(v, 0.5), int(c))
                    for v, c in zip(g["vec8"], g["canon"])]
    # canonical-aligned realized rate (realized_p1 is positional act0 rate)
    g["y_canon"] = [_flip_to_canonical(p, int(c))
                    for p, c in zip(g["realized_p1"].to_numpy(float), g["canon"])]
    # collapse to per-canonical-game means (game_code) so the unit is the game
    grp = g.groupby("game_code").agg(delta1c=("delta1c", "mean"),
                                     y_canon=("y_canon", "mean")).reset_index()
    x = grp["delta1c"].to_numpy(float)
    y = grp["y_canon"].to_numpy(float)
    lam, alpha = fit_lambda(x, y, "soft")
    lo, hi = boot_cluster_lambda(x, y, grp["game_code"].to_numpy(), "soft", n_boot=N_BOOT)
    return pd.DataFrame([{
        "agent": "griffiths", "axis": "cardinal (separate from rank lambda bar)",
        "lam_soft": lam, "alpha_soft": alpha, "ci_lo": lo, "ci_hi": hi,
        "n_games": int(len(grp)), "n_rows": int(len(g)),
        "note": "Griffiths cardinal-payoff robustness; do NOT compare to ordinal rank lambda",
    }])


# ===========================================================================
#  Figure
# ===========================================================================
def make_figure_legacy(agent_games, lambda_tbl, cv_full, cv_diag, fingerprint_tbl) -> None:
    from strategic_anatomy import paper_style as S
    S.apply()
    import matplotlib.pyplot as plt
    from matplotlib.lines import Line2D

    fig = plt.figure(figsize=(13.2, 4.5))
    gs = fig.add_gridspec(1, 3, width_ratios=[1.0, 1.25, 1.0],
                          left=0.06, right=0.985, bottom=0.14, top=0.80, wspace=0.30)
    ax_a = fig.add_subplot(gs[0])
    ax_b = fig.add_subplot(gs[1])
    ax_c = fig.add_subplot(gs[2])

    # ---------------- Panel (a): action-space lambda + soft calibration -----
    xx = np.linspace(-1.0, 2.0, 200)               # q=0.5 (L1/uniform) gap range is [-1, 2]
    for ag in AGENTS:
        d = agent_games[ag]
        row = lambda_tbl[lambda_tbl["agent"] == ag].iloc[0]
        col = COLOR[ag]
        is_h = ag == "nagel"
        y_action = d["s"].to_numpy(float) / d["n"].to_numpy(float)
        ax_a.scatter(d["delta1c_unif"], y_action, s=9, alpha=0.30 if not is_h else 0.45,
                     color=col, edgecolors="none", zorder=2,
                     marker="o" if not is_h else "D")
        lam_soft, alpha_soft = row["lam_soft_calibration"], row["alpha_soft_calibration"]
        if np.isfinite(lam_soft) and np.isfinite(alpha_soft):
            yy_soft = expit(alpha_soft + lam_soft * xx)
            ax_a.plot(xx, yy_soft, color=col, lw=1.4, ls=(0, (3, 2)),
                      alpha=0.32 if not is_h else 0.40, zorder=3)
        lam, alpha = row["lam_action"], row["alpha_action"]
        if np.isfinite(lam) and np.isfinite(alpha):
            yy = expit(alpha + lam * xx)
            ax_a.plot(xx, yy, color=col, lw=2.0 if not is_h else 1.8,
                      ls="-", zorder=4, label=f"{DISPLAY[ag]}  λ={lam:.2f}")
    ax_a.axhline(0.5, color="#999", lw=0.7, ls=":")
    ax_a.axvline(0.0, color="#999", lw=0.7, ls=":")
    ax_a.set_xlim(-1.05, 2.05)
    ax_a.set_ylim(-0.02, 1.02)
    ax_a.set_xlabel(r"canonical incentive gap  $\Delta_1^{c}$  (L1 belief, $q{=}0.5$)", fontsize=S.FS_AXIS)
    ax_a.set_ylabel(r"$P(\mathrm{canonical\ action})$", fontsize=S.FS_AXIS)
    ax_a.tick_params(labelsize=S.FS_TICK)
    model_legend = ax_a.legend(fontsize=5.7, frameon=False, loc="lower right",
                               handlelength=1.4, borderpad=0.2, labelspacing=0.25)
    ax_a.add_artist(model_legend)
    style_handles = [
        Line2D([0], [0], color="#333", lw=1.6, ls="-"),
        Line2D([0], [0], color="#333", lw=1.4, ls=(0, (3, 2)), alpha=0.38),
    ]
    ax_a.legend(style_handles, ["generated choices", "soft readout"],
                fontsize=5.6, frameon=False, loc="upper left", handlelength=1.6,
                borderpad=0.2, labelspacing=0.25)
    S.panel_title(ax_a, "a", "Quantal response (realized actions)")

    # ---------------- Panel (b): CV log-loss bars (full + diagnostic) -------
    nM = len(MODEL_ORDER)
    nA = len(AGENTS)
    grp_w = 0.86
    bw = grp_w / nA
    xbase = np.arange(nM)
    for j, ag in enumerate(AGENTS):
        means = [cv_full[ag][m][0] for m in MODEL_ORDER]
        los = [cv_full[ag][m][1] for m in MODEL_ORDER]
        his = [cv_full[ag][m][2] for m in MODEL_ORDER]
        xs = xbase + (j - (nA - 1) / 2.0) * bw
        yerr = np.vstack([np.array(means) - np.array(los), np.array(his) - np.array(means)])
        ax_b.bar(xs, means, width=bw * 0.92, color=COLOR[ag],
                 label=DISPLAY[ag], zorder=3,
                 edgecolor="white", lw=0.3)
        ax_b.errorbar(xs, means, yerr=np.abs(yerr), fmt="none", ecolor="#333",
                      elinewidth=0.6, capsize=1.4, zorder=5)
    ax_b.axhline(LOG2, color="#444", lw=1.0, ls="--", zorder=2)
    ax_b.text(nM - 0.5, LOG2 + 0.004, "chance (L0 = log 2)", ha="right", va="bottom",
              fontsize=5.8, color="#444")
    ax_b.set_xticks(xbase)
    ax_b.set_xticklabels(MODEL_ORDER, fontsize=S.FS_TICK)
    ax_b.set_ylabel("leave-games-out log-loss\n(lower = better)", fontsize=S.FS_AXIS)
    ax_b.tick_params(labelsize=S.FS_TICK)
    # y-window: show the informative band AND the NE 'catastrophic' bars (the point
    # of the panel), but let the extreme sharp-Lk bars clip -- they are annotated
    # off-scale so the reader knows they continue upward (exact values in the table).
    all_means = [cv_full[ag][m][0] for ag in AGENTS for m in MODEL_ORDER
                 if np.isfinite(cv_full[ag][m][0])]
    ne_max = max(cv_full[ag]["NE"][0] for ag in AGENTS if np.isfinite(cv_full[ag]["NE"][0]))
    lo_y = min(all_means) - 0.02
    hi_y = max(LOG2 + 0.04, ne_max + 0.12)            # always clear the worst NE bar
    ax_b.set_ylim(lo_y, hi_y)
    # mark any bar that runs off the top (the sharp-Lk catastrophes)
    for j, ag in enumerate(AGENTS):
        for mi, m in enumerate(MODEL_ORDER):
            v = cv_full[ag][m][0]
            if np.isfinite(v) and v > hi_y:
                x = mi + (j - (nA - 1) / 2.0) * bw
                ax_b.annotate("", xy=(x, hi_y - 0.005), xytext=(x, hi_y - 0.06),
                              arrowprops=dict(arrowstyle="-|>", color=COLOR[ag], lw=0.9),
                              zorder=6)
    ax_b.text(MODEL_ORDER.index("Lk"), hi_y - 0.01,
              f"Lk ↑ to {max(cv_full[a]['Lk'][0] for a in AGENTS):.1f}",
              ha="center", va="top", fontsize=5.2, color="#666", zorder=7)
    ax_b.legend(fontsize=5.6, frameon=False, loc="upper right", ncol=1,
                handlelength=1.1, borderpad=0.2, labelspacing=0.22)
    S.panel_title(ax_b, "b", "Model selection (predictive log-loss)")

    # ---------------- Panel (c): fingerprint (depth x precision scatter) ----
    for ag in AGENTS:
        r = fingerprint_tbl[fingerprint_tbl["agent"] == ag].iloc[0]
        depth = r["depth_pi"]
        lam = r["lambda_QLk"]
        col = COLOR[ag]
        if r["is_degenerate"]:
            ax_c.scatter([0], [0], s=70, color=col, marker="X", zorder=5,
                         edgecolors="k", linewidths=0.5)
            ax_c.annotate("no belief formation\n(λ≈0)", (0, 0),
                          textcoords="offset points", xytext=(8, 4),
                          fontsize=5.6, color=col)
            continue
        if not (np.isfinite(depth) and np.isfinite(lam)):
            continue
        xlo, xhi = r["depth_lo"], r["depth_hi"]
        ylo, yhi = r["lam_lo"], r["lam_hi"]
        ax_c.errorbar([depth], [lam],
                      xerr=[[depth - xlo], [xhi - depth]] if np.isfinite(xlo) else None,
                      yerr=[[lam - ylo], [yhi - lam]] if np.isfinite(ylo) else None,
                      fmt="o", ms=8, color=col, ecolor=col, elinewidth=1.0,
                      capsize=2, mec="k", mew=0.5, zorder=5,
                      label=DISPLAY[ag])
    # Nash corner marker (precision -> inf, depth -> inf)
    ax_c.annotate("Nash\n(λ→∞, depth→∞)", xy=(0.98, 0.98), xycoords="axes fraction",
                  ha="right", va="top", fontsize=5.8, color="#555",
                  fontstyle="italic")
    ax_c.scatter([], [])  # keep axes
    ax_c.set_xlabel(r"reasoning depth  ($\sum_k k\,\pi_k$, QLk)", fontsize=S.FS_AXIS)
    ax_c.set_ylabel(r"response precision  $\lambda_{\mathrm{QLk}}$", fontsize=S.FS_AXIS)
    ax_c.tick_params(labelsize=S.FS_TICK)
    ax_c.set_xlim(-0.15, max(2.2, fingerprint_tbl["depth_pi"].max(skipna=True) * 1.15 + 0.2))
    ax_c.legend(fontsize=5.6, frameon=False, loc="upper left",
                handlelength=1.0, borderpad=0.2, labelspacing=0.25)
    S.panel_title(ax_c, "c", "Bounded-rationality fingerprint")

    # ---------------- figure title ----------------
    S.figure_titles(
        fig,
        "From equilibrium to bounded reasoning: a depth x sharpness account of LLM strategy",
        "(a) action-space quantal response  ·  (b) leave-games-out model selection  ·  (c) depth x sharpness fingerprint",
    )

    for ext in ("png", "pdf"):
        fig.savefig(FIG_DIR / f"fig3_qre_to_levelk.{ext}", dpi=300)
    plt.close(fig)
    print(f"\nwrote {FIG_DIR / 'fig3_qre_to_levelk.png'}")
    print(f"wrote {FIG_DIR / 'fig3_qre_to_levelk.pdf'}")


RULE_LABEL = {
    "Nash Equilibrium": "Nash", "RDNE": "RDNE", "PDNE": "PDNE",
    "Level-1": "L1", "Level-2": "L2", "Level-3": "L3",
    "Level-1 Alpha": "L1α", "Level-2 Alpha": "L2α", "Level-5 Alpha": "L5α",
    "Near-Equal Split": "NES", "cNES": "cNES", "rNES": "rNES",
    "Soc-Max": "SocMax", "Pareto Efficiency": "Pareto",
}


def _compact_decimal(x: float) -> str:
    s = f"{x:.2f}"
    return s.replace("0.", ".").replace("-0.", "-.")


def _ols_intercept_slope(x: np.ndarray, y: np.ndarray) -> tuple[float, float]:
    X = np.column_stack([np.ones(len(x)), x])
    beta = np.linalg.lstsq(X, y, rcond=None)[0]
    return float(beta[0]), float(beta[1])


def _partial_complexity(x_complexity: np.ndarray, x_delta: np.ndarray,
                        y: np.ndarray) -> tuple[float, float]:
    """Return the complexity coefficient and partial Pearson correlation.

    The coefficient is from ``y ~ 1 + delta1c + complexity``.  The partial
    correlation is Pearson's r between the residuals from regressing ``y`` and
    ``complexity`` separately on ``1 + delta1c``.
    """
    X = np.column_stack([np.ones(len(y)), x_delta, x_complexity])
    beta = np.linalg.lstsq(X, y, rcond=None)[0]
    base = np.column_stack([np.ones(len(y)), x_delta])
    y_resid = y - base @ np.linalg.lstsq(base, y, rcond=None)[0]
    x_resid = x_complexity - base @ np.linalg.lstsq(base, x_complexity, rcond=None)[0]
    r = np.nan
    if np.std(x_resid) > 1e-10 and np.std(y_resid) > 1e-10:
        r = float(np.corrcoef(x_resid, y_resid)[0, 1])
    return float(beta[2]), r


def _clean_xy(d: pd.DataFrame) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    x = d["complexity_score"].to_numpy(float)
    y = d["s"].to_numpy(float) / d["n"].to_numpy(float)
    z = d["delta1c_unif"].to_numpy(float)
    ok = np.isfinite(x) & np.isfinite(y) & np.isfinite(z)
    return x[ok], y[ok], z[ok]


def _bootstrap_response(x: np.ndarray, y: np.ndarray, z: np.ndarray) -> dict[str, float]:
    rng = np.random.default_rng(SEED)
    slope_vals, rho_vals, partial_slope_vals, partial_r_vals = [], [], [], []
    n = len(y)
    for _ in range(N_BOOT):
        idx = rng.integers(0, n, size=n)
        xb, yb, zb = x[idx], y[idx], z[idx]
        if np.std(xb) <= 1e-10 or np.std(yb) <= 1e-10:
            continue
        _, slope = _ols_intercept_slope(xb, yb)
        rho = spearmanr(xb, yb).correlation
        ps, pr = _partial_complexity(xb, zb, yb)
        slope_vals.append(slope)
        rho_vals.append(rho)
        partial_slope_vals.append(ps)
        partial_r_vals.append(pr)

    def ci(vals):
        vals = np.asarray(vals, float)
        vals = vals[np.isfinite(vals)]
        if vals.size == 0:
            return np.nan, np.nan
        return float(np.percentile(vals, 2.5)), float(np.percentile(vals, 97.5))

    slo, shi = ci(slope_vals)
    rlo, rhi = ci(rho_vals)
    pslo, pshi = ci(partial_slope_vals)
    prlo, prhi = ci(partial_r_vals)
    return {
        "slope_ci_lo": slo, "slope_ci_hi": shi,
        "rho_ci_lo": rlo, "rho_ci_hi": rhi,
        "partial_slope_ci_lo": pslo, "partial_slope_ci_hi": pshi,
        "partial_r_ci_lo": prlo, "partial_r_ci_hi": prhi,
    }


def build_complexity_response(agent_games: dict[str, pd.DataFrame]) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    summary_rows = []
    bin_rows = []
    partial_rows = []
    for ag in AGENTS:
        d = agent_games[ag].copy()
        x, y, z = _clean_xy(d)
        intercept, slope = _ols_intercept_slope(x, y)
        rho = float(spearmanr(x, y).correlation)
        partial_slope, partial_r = _partial_complexity(x, z, y)
        boot = _bootstrap_response(x, y, z)
        summary_rows.append({
            "agent": ag, "display": DISPLAY[ag], "subset": "all",
            "n_games": int(len(y)), "intercept": intercept, "slope": slope,
            "spearman_rho": rho, "partial_slope_ctrl_delta1c": partial_slope,
            "partial_r_ctrl_delta1c": partial_r, **boot,
        })

        plot_df = pd.DataFrame({"complexity_score": x, "p_canon": y})
        plot_df["bin"] = pd.qcut(plot_df["complexity_score"], q=5, labels=False, duplicates="drop")
        for b, sub in plot_df.groupby("bin", sort=True):
            bin_rows.append({
                "agent": ag, "display": DISPLAY[ag], "bin": int(b),
                "n_games": int(len(sub)),
                "complexity_mean": float(sub["complexity_score"].mean()),
                "p_canon_mean": float(sub["p_canon"].mean()),
                "p_canon_se": float(sub["p_canon"].std(ddof=1) / math.sqrt(len(sub))) if len(sub) > 1 else np.nan,
            })

        for subset, families in {
            "all": None,
            "dominance_solvable": {"DD", "OD1", "OD2"},
        }.items():
            sd = d if families is None else d[d["family"].isin(families)]
            sx, sy, sz = _clean_xy(sd)
            ps, pr = _partial_complexity(sx, sz, sy)
            sb = _bootstrap_response(sx, sy, sz)
            partial_rows.append({
                "agent": ag, "display": DISPLAY[ag], "subset": subset,
                "n_games": int(len(sy)),
                "partial_slope_ctrl_delta1c": ps,
                "partial_slope_ci_lo": sb["partial_slope_ci_lo"],
                "partial_slope_ci_hi": sb["partial_slope_ci_hi"],
                "partial_r_ctrl_delta1c": pr,
                "partial_r_ci_lo": sb["partial_r_ci_lo"],
                "partial_r_ci_hi": sb["partial_r_ci_hi"],
                "spearman_rho_raw": float(spearmanr(sx, sy).correlation),
                "spearman_rho_raw_ci_lo": sb["rho_ci_lo"],
                "spearman_rho_raw_ci_hi": sb["rho_ci_hi"],
            })

    summary = pd.DataFrame(summary_rows)
    bins = pd.DataFrame(bin_rows)
    partial = pd.DataFrame(partial_rows)
    summary.to_csv(TAB_DIR / "f3_complexity_response.csv", index=False)
    bins.to_csv(TAB_DIR / "f3_complexity_bins.csv", index=False)
    partial.to_csv(TAB_DIR / "f3_complexity_partial.csv", index=False)
    return summary, bins, partial


def _agent_action_rate(d: pd.DataFrame) -> np.ndarray:
    if "p_action" in d:
        return d["p_action"].to_numpy(float)
    return d["s"].to_numpy(float) / d["n"].to_numpy(float)


def _boot_pearson(x: np.ndarray, y: np.ndarray) -> tuple[float, float, float]:
    x = np.asarray(x, float)
    y = np.asarray(y, float)
    ok = np.isfinite(x) & np.isfinite(y)
    x = x[ok]
    y = y[ok]
    if len(x) < 5 or np.std(x) <= 1e-10 or np.std(y) <= 1e-10:
        return np.nan, np.nan, np.nan
    r = float(pearsonr(x, y)[0])
    rng = np.random.default_rng(SEED)
    vals = []
    for _ in range(N_BOOT):
        idx = rng.integers(0, len(x), size=len(x))
        if np.std(x[idx]) <= 1e-10 or np.std(y[idx]) <= 1e-10:
            continue
        vals.append(float(pearsonr(x[idx], y[idx])[0]))
    if not vals:
        return r, np.nan, np.nan
    lo, hi = np.percentile(vals, [2.5, 97.5])
    return r, float(lo), float(hi)


def human_alignment_table(agent_games: dict[str, pd.DataFrame]) -> tuple[pd.DataFrame, pd.DataFrame]:
    wide = pd.DataFrame(index=agent_games["nagel"]["game_code"].to_numpy())
    wide.index.name = "game_code"
    wide["nagel"] = _agent_action_rate(agent_games["nagel"])
    for model in LLMS:
        d = agent_games[model]
        wide[model] = pd.Series(_agent_action_rate(d), index=d["game_code"].to_numpy())

    rows = []
    for model in LLMS:
        d = wide[["nagel", model]].dropna()
        x = d["nagel"].to_numpy(float)
        y = d[model].to_numpy(float)
        r, lo, hi = _boot_pearson(x, y)
        rho = float(spearmanr(x, y).correlation) if len(d) >= 5 else np.nan
        rows.append({
            "model": model,
            "agent": DISPLAY[model],
            "n_games": int(len(d)),
            "pearson_r_hard": r,
            "pearson_lo": lo,
            "pearson_hi": hi,
            "spearman_rho_hard": rho,
        })
    tab = pd.DataFrame(rows)
    tab.to_csv(TAB_DIR / "f1_human_corr.csv", index=False)
    return wide, tab


def _qlk_arrays(df: pd.DataFrame) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return binomial counts and canonical-signed QLk gaps for one agent."""
    s = df["s"].to_numpy(float)
    n = df["n"].to_numpy(float)
    G = df[["gap_L1", "gap_L2", "gap_L3"]].to_numpy(float)
    if not (np.all(np.isfinite(s)) and np.all(np.isfinite(n)) and np.all(np.isfinite(G))):
        raise AssertionError("non-finite QLk fingerprint inputs")
    return s, n, G


def _qlk_pcanon_array(pi: np.ndarray, lam: float, G: np.ndarray) -> np.ndarray:
    return _clip(pi[0] * 0.5
                 + pi[1] * expit(lam * G[:, 0])
                 + pi[2] * expit(lam * G[:, 1])
                 + pi[3] * expit(lam * G[:, 2]))


def fit_qlk_sharpness(s: np.ndarray, n: np.ndarray, G: np.ndarray,
                      multi: bool = False) -> dict[str, float]:
    """Fit QLk on arrays and report depth plus probability-scale sharpness.

    This is the same QLk model family as ``fit_model("QLk", ...)`` but avoids
    DataFrame overhead inside the bootstrap used for panel b.
    """
    starts = [[0, 0, 0, 1.0]]
    if multi:
        starts += [[0, 0, 0, 0.3], [0.5, 0.5, 0.5, 2.0],
                   [-0.5, 0.7, 0.7, 2.0], [0.0, -0.7, 1.1, 2.5]]

    def f(th):
        pi = _softmax_simplex(np.asarray(th[:3], float))
        p = _qlk_pcanon_array(pi, float(th[3]), G)
        return _nll(p, s, n)

    x, _ = _fit_restarts(f, starts, bounds=[(-8, 8), (-8, 8), (-8, 8), (0.0, 50.0)])
    if x is None:
        pi = np.full(4, 0.25)
        lam = np.nan
        p = np.full(len(s), 0.5)
    else:
        pi = _softmax_simplex(x[:3])
        lam = float(x[3])
        p = _qlk_pcanon_array(pi, lam, G)
    return {
        "depth_pi": float(sum(k * pi[k] for k in range(4))),
        "sharpness": float(np.mean(np.maximum(p, 1.0 - p))),
        "lambda_QLk": lam,
        "pi_L0": float(pi[0]), "pi_L1": float(pi[1]),
        "pi_L2": float(pi[2]), "pi_L3": float(pi[3]),
        "lambda_QLk_boundary": bool(np.isfinite(lam) and lam >= 49.0),
    }


def boot_qlk_sharpness(s: np.ndarray, n: np.ndarray, G: np.ndarray,
                       n_boot: int = N_BOOT_FINGERPRINT, seed: int = SEED) -> dict[str, tuple[float, float]]:
    """Bootstrap-by-game CIs for the QLk depth/sharpness panel."""
    rng = np.random.default_rng(seed + 11)
    vals: dict[str, list[float]] = {"depth_pi": [], "sharpness": [], "lambda_QLk": []}
    for _ in range(n_boot):
        idx = rng.integers(0, len(s), size=len(s))
        try:
            fp = fit_qlk_sharpness(s[idx], n[idx], G[idx], multi=False)
        except Exception:
            continue
        for key in vals:
            v = fp[key]
            if np.isfinite(v):
                vals[key].append(float(v))

    out = {}
    for key, arr in vals.items():
        a = np.asarray(arr, float)
        if a.size:
            out[key] = (float(np.percentile(a, 2.5)), float(np.percentile(a, 97.5)))
        else:
            out[key] = (np.nan, np.nan)
    return out


def qlk_landmarks(df: pd.DataFrame) -> dict[str, float]:
    """Deterministic pure-level sharpness references over the same game set."""
    out = {"L0": 0.5}
    for level in LEVELS:
        g = df[f"gap_{level}"].to_numpy(float)
        p = expit(1e6 * g)
        out[level] = float(np.mean(np.maximum(p, 1.0 - p)))
    return out


def build_fingerprint_table(agent_games: dict[str, pd.DataFrame]) -> pd.DataFrame:
    rows = []
    for ag in AGENTS:
        s, n, G = _qlk_arrays(agent_games[ag])
        fp = fit_qlk_sharpness(s, n, G, multi=True)
        ci = boot_qlk_sharpness(s, n, G)
        rows.append({
            "agent": ag,
            "display": DISPLAY[ag],
            **fp,
            "depth_pi_ci_lo": ci["depth_pi"][0],
            "depth_pi_ci_hi": ci["depth_pi"][1],
            "sharpness_ci_lo": ci["sharpness"][0],
            "sharpness_ci_hi": ci["sharpness"][1],
            "lambda_QLk_ci_lo": ci["lambda_QLk"][0],
            "lambda_QLk_ci_hi": ci["lambda_QLk"][1],
            "n_games": int(agent_games[ag]["game_code"].nunique()),
            "ci_method": f"bootstrap by game, n={N_BOOT_FINGERPRINT}; panel y is mean modal-action probability",
        })
    out = pd.DataFrame(rows)
    out.to_csv(TAB_DIR / "f3_fingerprint.csv", index=False)
    return out


def make_figure(agent_games, lambda_tbl, fingerprint_tbl: pd.DataFrame) -> None:
    from strategic_anatomy import paper_style as S
    S.apply()
    import matplotlib.pyplot as plt
    from matplotlib.lines import Line2D
    from matplotlib.patches import Ellipse

    fig = plt.figure(figsize=(S.NHB_TEXTWIDTH_IN, 3.50))
    gs = fig.add_gridspec(1, 2, width_ratios=[1.38, 1.0],
                          left=S.NHB_FIG3_LEFT, right=S.NHB_FIG3_RIGHT,
                          bottom=S.NHB_FIG3_BOTTOM, top=S.NHB_FIG3_TOP, wspace=0.16)
    ax_a = fig.add_subplot(gs[0])
    fs_panel = S.NHB_FS_PANEL
    fs_axis = S.NHB_FS_AXIS_LARGE
    fs_tick = S.NHB_FS_TICK_SMALL
    fs_mini_title = S.NHB_FS_MINI_TITLE
    fs_stat = S.NHB_FS_INSET_STAT

    # ---------------- Panel (a): action-space lambda + soft calibration -----
    all_x = np.concatenate([agent_games[ag]["delta1c_unif"].to_numpy(float) for ag in AGENTS])
    xx = np.linspace(float(np.nanmin(all_x)) - 0.05, float(np.nanmax(all_x)) + 0.05, 240)
    label_x = xx[-1] + 0.09
    lambda_label_y = {
        "gptoss": 0.985,
        "qwen_instruct": 0.945,
        "qwen": 0.875,
        "nagel": 0.815,
        "llama31_instruct": 0.650,
    }
    for ag in AGENTS:
        d = agent_games[ag]
        row = lambda_tbl[lambda_tbl["agent"] == ag].iloc[0]
        col = COLOR[ag]
        is_h = ag == "nagel"
        y_action = d["s"].to_numpy(float) / d["n"].to_numpy(float)
        ax_a.scatter(d["delta1c_unif"], y_action, s=9, alpha=0.30 if not is_h else 0.45,
                     color=col, edgecolors="none", zorder=2,
                     marker="o" if not is_h else "D")
        lam_soft, alpha_soft = row["lam_soft_calibration"], row["alpha_soft_calibration"]
        if not is_h and np.isfinite(lam_soft) and np.isfinite(alpha_soft):
            ax_a.plot(xx, expit(alpha_soft + lam_soft * xx), color=col, lw=1.4,
                      ls=(0, (3, 2)), alpha=0.28, zorder=3)
        lam, alpha = row["lam_action"], row["alpha_action"]
        if np.isfinite(lam) and np.isfinite(alpha):
            ls = (0, (3, 2)) if is_h else "-"
            ax_a.plot(xx, expit(alpha + lam * xx), color=col, lw=1.55,
                      ls=ls, zorder=4)
            y_end = float(expit(alpha + lam * xx[-1]))
            y_label = lambda_label_y.get(ag, y_end)
            if abs(y_label - y_end) > 0.012:
                ax_a.plot([xx[-1], label_x - 0.025], [y_end, y_label],
                          color=col, lw=0.45, alpha=0.65, zorder=4,
                          clip_on=False)
            ax_a.text(label_x, y_label,
                      f"{_compact_decimal(lam)}", color=col,
                      fontsize=6.0, ha="left", va="center", clip_on=False,
                      bbox=dict(facecolor="white", edgecolor="none", alpha=0.72, pad=0.15))
    ax_a.axhline(0.5, color="#999", lw=0.7, ls=":")
    ax_a.axvline(0.0, color="#999", lw=0.7, ls=":")
    ax_a.set_xlim(xx[0], xx[-1] + 0.42)
    ax_a.set_ylim(-0.02, 1.02)
    ax_a.set_xlabel(r"canonical incentive gap  $\Delta_1^{c}$", fontsize=fs_axis)
    ax_a.set_ylabel(r"$P(\mathrm{canonical\ action})$", fontsize=fs_axis)
    S.nhb_panel_title(ax_a, "a", "Incentive response (quantal sensitivity λ)",
                      fontsize=fs_panel)

    # ---------------- Panel (b): bounded-rationality map -------------------
    ax_b = fig.add_subplot(gs[1])
    R = fingerprint_tbl.set_index("agent")
    lm = qlk_landmarks(agent_games["qwen"])
    ax_b.axhline(0.5, color="#bbb", ls=":", lw=0.75, zorder=1)
    ax_b.text(3.12, 0.505, "chance", fontsize=5.7, color="#888",
              ha="right", va="bottom")

    # Pure-level reference landmarks. These are discrete archetypes, not a line
    # or an achievable ceiling for mixtures.
    ax_b.scatter([0, 1, 2, 3], [lm["L0"], lm["L1"], lm["L2"], lm["L3"]],
                 marker="D", s=22, color="#8a8a8a", zorder=2)
    for x, y, lab, off, ha in [
        (0, lm["L0"], "Random\n(L0)", (9, 7), "left"),
        (1, lm["L1"], "deterministic\nL1", (-5, 7), "right"),
        (2, lm["L2"], "deterministic\nL2", (0, 7), "center"),
        (3, lm["L3"], "deterministic\nL3", (13, 7), "right"),
    ]:
        ax_b.annotate(lab, (x, y), textcoords="offset points", xytext=off,
                      ha=ha, va="bottom", fontsize=5.6, color="#777")
    ax_b.annotate("idealized deep,\ndeterministic limit", (2.58, 0.962),
                  fontsize=5.6, color="#555", style="italic", ha="center", va="top")
    ax_b.annotate("grey diamonds: pure level-k references", (3.12, 0.468),
                  fontsize=5.0, color="#9a9a9a", ha="right")

    # Dense LLMs + human form one overlapping CI group; shade the union.
    cluster = ["qwen", "qwen_instruct", "llama31_instruct", "nagel"]
    dlo = R.loc[cluster, "depth_pi_ci_lo"].min()
    dhi = R.loc[cluster, "depth_pi_ci_hi"].max()
    slo = R.loc[cluster, "sharpness_ci_lo"].min()
    shi = R.loc[cluster, "sharpness_ci_hi"].max()
    if np.all(np.isfinite([dlo, dhi, slo, shi])):
        ax_b.add_patch(Ellipse(((dlo + dhi) / 2, (slo + shi) / 2),
                               max(dhi - dlo, 0.01), max(shi - slo, 0.01),
                               facecolor="#888", alpha=0.09, edgecolor="#aaa",
                               ls="--", lw=0.65, zorder=1))
        ax_b.annotate("dense LLMs + human\n95% CIs overlap",
                      ((dlo + dhi) / 2, slo - 0.030), ha="center", va="top",
                      fontsize=5.4, color="#777")

    lab_off = {
        "qwen": (7, 10),
        "qwen_instruct": (8, -14),
        "llama31_instruct": (-11, 13),
        "nagel": (-17, -1),
        "gptoss": (-8, 13),
    }
    label_box = dict(facecolor="white", edgecolor="none", alpha=0.72, pad=0.14)
    for ag, r in R.iterrows():
        x = float(r["depth_pi"])
        y = float(r["sharpness"])
        if not np.isfinite(x) or not np.isfinite(y):
            continue
        col = COLOR[ag]
        xerr = np.array([[x - float(r["depth_pi_ci_lo"])],
                         [float(r["depth_pi_ci_hi"]) - x]])
        yerr = np.array([[y - float(r["sharpness_ci_lo"])],
                         [float(r["sharpness_ci_hi"]) - y]])
        xerr = np.where(np.isfinite(xerr) & (xerr >= 0), xerr, 0.0)
        yerr = np.where(np.isfinite(yerr) & (yerr >= 0), yerr, 0.0)
        ax_b.errorbar(x, y, xerr=xerr, yerr=yerr, fmt="none", ecolor=col,
                      elinewidth=0.75, alpha=0.75, capsize=1.8, zorder=4)
        ax_b.scatter(x, y, s=36 if ag == "gptoss" else 31, color=col,
                     marker="D" if ag == "nagel" else "o",
                     edgecolor="white", linewidth=0.5, zorder=5)
        dx, dy = lab_off.get(ag, (5, 4))
        ax_b.annotate(DISPLAY[ag], (x, y), textcoords="offset points",
                      xytext=(dx, dy), ha="left" if dx >= 0 else "right",
                      va="center", fontsize=6.0,
                      fontweight="bold" if ag == "gptoss" else "normal",
                      color=col, bbox=label_box,
                      arrowprops=dict(arrowstyle="-", color=col, lw=0.36,
                                      alpha=0.55, shrinkA=2, shrinkB=3)
                      if ag != "gptoss" else None)
    if "gptoss" in R.index:
        g = R.loc["gptoss"]
        ax_b.annotate(f"L2/L3 mix\nL0 weight ≈ {g['pi_L0'] * 100:.0f}%",
                      (float(g["depth_pi"]), float(g["sharpness"])),
                      textcoords="offset points", xytext=(8, -16),
                      ha="left", va="top", fontsize=5.4, color="#6b4fa0",
                      bbox=label_box,
                      arrowprops=dict(arrowstyle="-", color="#6b4fa0", lw=0.38,
                                      alpha=0.55, shrinkA=2, shrinkB=3))

    ax_b.set_xlim(-0.10, 3.18)
    ax_b.set_ylim(0.45, 0.995)
    ax_b.set_xlabel("reasoning depth\n(quantal level-k mixture)", fontsize=fs_axis)
    ax_b.set_ylabel("decision sharpness\nmean modal-action probability", fontsize=fs_axis)
    S.nhb_panel_title(ax_b, "b", "Bounded-rationality map",
                      fontsize=fs_panel)

    for ax in (ax_a, ax_b):
        ax.spines[["top", "right"]].set_visible(False)
        ax.spines[["left", "bottom"]].set_linewidth(0.6)
        ax.tick_params(labelsize=fs_tick, width=0.55, length=2)
        ax.grid(axis="y", color="#dedede", linewidth=0.45, alpha=0.8)

    legend_handles = []
    for ag in AGENTS:
        legend_handles.append(Line2D([0], [0], color=COLOR[ag], lw=1.6,
                                     ls=(0, (3, 2)) if ag == "nagel" else "-",
                                     marker="D" if ag == "nagel" else "o",
                                     markersize=4.0, label=DISPLAY[ag]))
    legend_handles.extend([
        Line2D([0], [0], color="#333", lw=1.3, ls="-", label="generated decision"),
        Line2D([0], [0], color="#333", lw=1.2, ls=(0, (3, 2)), alpha=0.30,
               label="soft-policy readout"),
    ])
    fig.legend(legend_handles, [h.get_label() for h in legend_handles],
               loc="upper center", bbox_to_anchor=(0.5, S.NHB_LEGEND_Y),
               ncol=7, frameon=False, fontsize=6.6, handlelength=1.15,
               handletextpad=0.30, columnspacing=0.65)

    with plt.rc_context({"savefig.bbox": None}):
        for ext in ("png", "pdf"):
            fig.savefig(FIG_DIR / f"fig3_qre_to_levelk.{ext}",
                        dpi=600 if ext == "png" else 300, bbox_inches=None)
    plt.close(fig)
    print(f"\nwrote {FIG_DIR / 'fig3_qre_to_levelk.png'}")
    print(f"wrote {FIG_DIR / 'fig3_qre_to_levelk.pdf'}")


def make_model_selection_supplement(cv_full) -> None:
    from strategic_anatomy import paper_style as S
    S.apply()
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(7.4, 3.4))
    nM = len(MODEL_ORDER)
    nA = len(AGENTS)
    grp_w = 0.86
    bw = grp_w / nA
    xbase = np.arange(nM)
    for j, ag in enumerate(AGENTS):
        means = [cv_full[ag][m][0] for m in MODEL_ORDER]
        los = [cv_full[ag][m][1] for m in MODEL_ORDER]
        his = [cv_full[ag][m][2] for m in MODEL_ORDER]
        xs = xbase + (j - (nA - 1) / 2.0) * bw
        yerr = np.vstack([np.array(means) - np.array(los), np.array(his) - np.array(means)])
        ax.bar(xs, means, width=bw * 0.92, color=COLOR[ag], label=DISPLAY[ag],
               zorder=3, edgecolor="white", lw=0.3, hatch=None, alpha=1.0)
        ax.errorbar(xs, means, yerr=np.abs(yerr), fmt="none", ecolor="#333",
                    elinewidth=0.6, capsize=1.4, zorder=5)
    ax.axhline(LOG2, color="#444", lw=1.0, ls="--", zorder=2)
    ax.text(nM - 0.5, LOG2 + 0.004, "chance (L0 = log 2)", ha="right", va="bottom",
            fontsize=5.8, color="#444")
    ax.set_xticks(xbase)
    ax.set_xticklabels(MODEL_ORDER, fontsize=S.FS_TICK)
    ax.set_ylabel("leave-games-out log-loss\n(lower = better)", fontsize=S.FS_AXIS)
    ax.tick_params(labelsize=S.FS_TICK)
    all_means = [cv_full[ag][m][0] for ag in AGENTS for m in MODEL_ORDER if np.isfinite(cv_full[ag][m][0])]
    ax.legend(fontsize=5.8, frameon=False, ncol=2, loc="upper right",
              handlelength=1.0, borderpad=0.2, labelspacing=0.25, columnspacing=0.8)
    # This is a standalone supplementary figure, not a panel.  Avoid the
    # generic panel-letter prefix, which otherwise rendered as an unexplained
    # ``(S)`` in the figure title.
    ax.set_title("Leave-games-out behavioural-model comparison",
                 fontsize=S.FS_PANEL, loc="left", fontweight="bold",
                 color=S.INK, pad=6.0)
    all_his = [cv_full[ag][m][2] for ag in AGENTS for m in MODEL_ORDER
               if np.isfinite(cv_full[ag][m][2])]
    ax.set_ylim(min(all_means) - 0.02, max(LOG2 + 0.04, max(all_his) + 0.03))
    fig.tight_layout()
    for ext in ("png", "pdf"):
        fig.savefig(FIG_DIR / f"figS_model_selection.{ext}", dpi=300)
    plt.close(fig)
    print(f"wrote {FIG_DIR / 'figS_model_selection.png'}")
    print(f"wrote {FIG_DIR / 'figS_model_selection.pdf'}")


# ===========================================================================
#  Main
# ===========================================================================
def _selfcheck_vectorization(agent_games) -> None:
    """Assert the vectorized gaps reproduce the scalar delta1/delta2 (single source
    of truth from oneshot_common) on a sample of games + beliefs."""
    d = agent_games["qwen"]
    U1, U2, _ = _payoff_stack(d)
    rng = np.random.default_rng(0)
    for q in [0.0, 0.25, 0.5, 0.73, 1.0]:
        qa = np.full(U1.shape[0], q)
        v1 = _vdelta1(U1, qa)
        v2 = _vdelta2(U2, qa)
        s1 = np.array([delta1(v, q) for v in d["vec8"]])
        s2 = np.array([delta2(v, q) for v in d["vec8"]])
        assert np.allclose(v1, s1, atol=1e-9), f"vdelta1 mismatch at q={q}"
        assert np.allclose(v2, s2, atol=1e-9), f"vdelta2 mismatch at q={q}"
    print("  [selfcheck] vectorized delta1/delta2 == scalar oneshot_common (OK)")


def main() -> int:
    np.seterr(over="ignore", invalid="ignore")
    print("=" * 78)
    print("Figure 3 — incentive response and bounded-rationality fingerprint   (canonical action axis)")
    print("=" * 78)
    agent_games = build_agent_games()
    for ag in AGENTS:
        d = agent_games[ag]
        print(f"  [{ag:18s}] {len(d):3d} games  | mean p_canon(soft)={d['pbar'].mean():.3f}"
              f"  | mean p_canon(action)={(d['s'] / d['n']).mean():.3f}")
    human_row, _ = HL.fit_human_lambda()

    # ---- (1) f3_lambda: ONE consistent belief basis = q=0.5 ----------------
    # HEADLINE: action-space lambda fit to realized/generated canonical choices at
    # q=0.5 for EVERY agent. LLM rows use generated/commit counterbalance cells;
    # Moore et al. uses individual MGN decisions. This is the revealed behavioral
    # precision and the panel (a) curve. Soft token-probability lambda is retained
    # for LLM calibration/readout robustness, never the behavioral headline.
    lam_rows = []
    for ag in AGENTS:
        d = agent_games[ag]
        pbar = d["pbar"].to_numpy(float)
        g = d["game_code"].to_numpy()
        x_q05 = d["delta1c_unif"].to_numpy(float)        # HEADLINE basis: q=0.5
        x_eq2 = d["delta1c"].to_numpy(float)             # same q=0.5 basis in this corrected build
        if ag == "nagel":
            lam_a = float(human_row["lambda"])
            a_a = float(human_row["alpha"])
            lo_a = float(human_row["lambda_boot_game_lo"])
            hi_a = float(human_row["lambda_boot_game_hi"])
            lam_s = a_s = lo_s = hi_s = np.nan
            lam_e = a_e = lo_e = hi_e = np.nan
            n_observations = int(human_row["n_obs"])
            n_sessions = int(human_row["n_sessions"])
            n_unique_participants = int(human_row["n_unique_participants"])
            ci_method = "individual decisions; bootstrap by game; session-clustered CI in f3_human_lambda.csv"
        else:
            # action-space headline (q=0.5): expand per-game counts so the GLM sees
            # the actual generated/commit decisions from the counterbalance cells.
            xh, yh, gh = [], [], []
            for _, r in d.iterrows():
                n = int(r["n"])
                s = int(r["s"])
                xh += [r["delta1c_unif"]] * n
                yh += [1] * s + [0] * (n - s)
                gh += [r["game_code"]] * n
            xh = np.array(xh)
            yh = np.array(yh)
            gh = np.array(gh)
            lam_a, a_a = fit_lambda(xh, yh, "hard")
            lo_a, hi_a = boot_cluster_lambda(xh, yh, gh, "hard", n_boot=N_BOOT)
            # soft calibration/readout fit (q=0.5)
            lam_s, a_s = fit_lambda(x_q05, pbar, "soft")
            lo_s, hi_s = boot_cluster_lambda(x_q05, pbar, g, "soft", n_boot=N_BOOT)
            # soft calibration/readout robustness (empirical-q2 belief)
            lam_e, a_e = fit_lambda(x_eq2, pbar, "soft")
            lo_e, hi_e = boot_cluster_lambda(x_eq2, pbar, g, "soft", n_boot=N_BOOT)
            n_observations = int(d["n"].sum())
            n_sessions = np.nan
            n_unique_participants = np.nan
            ci_method = "counterbalance decisions; bootstrap by game"
        lam_rows.append({
            "agent": ag, "display": DISPLAY[ag],
            "belief_q": "q=0.5",
            "lam_action": lam_a, "lam_action_ci_lo": lo_a, "lam_action_ci_hi": hi_a,
            "alpha_action": a_a,
            "lam_soft_calibration": lam_s,
            "lam_soft_calibration_ci_lo": lo_s, "lam_soft_calibration_ci_hi": hi_s,
            "alpha_soft_calibration": a_s,
            "lam_soft_empq2_calibration": lam_e,
            "lam_soft_empq2_ci_lo": lo_e, "lam_soft_empq2_ci_hi": hi_e,
            "alpha_soft_empq2": a_e,
            "n_games": int(len(d)),
            "n_observations": n_observations,
            "n_sessions": n_sessions,
            "n_unique_participants": n_unique_participants,
            "ci_method": ci_method,
        })
    lambda_tbl = pd.DataFrame(lam_rows)
    lambda_tbl.to_csv(TAB_DIR / "f3_lambda.csv", index=False)

    print("\n--- f3_lambda (HEADLINE action-space λ @ q=0.5; soft = calibration) ---")
    print(lambda_tbl[["agent", "belief_q", "lam_action", "lam_action_ci_lo", "lam_action_ci_hi",
                      "lam_soft_calibration", "lam_soft_empq2_calibration", "n_games"]]
          .round(3).to_string(index=False))

    # ---- (2) complexity robustness tables --------------------------------
    # Keep the incentive-adjusted tables on the same corrected 144-game panel
    # as Figure 1d.  These tables are supplementary robustness outputs; Figure
    # 1d itself remains the raw Spearman association generated by
    # figscripts/fig1_rationality.py.
    complexity_tbl, _, _ = build_complexity_response(agent_games)
    print("\n--- complexity response (raw rho; partial r controls delta1c) ---")
    print(complexity_tbl[["agent", "n_games", "spearman_rho", "partial_r_ctrl_delta1c",
                          "partial_r_ci_lo", "partial_r_ci_hi"]]
          .round(3).to_string(index=False))

    # ---- (3) leave-games-out model selection -----------------------------
    print("\n--- leave-games-out model selection (10-fold GroupKFold by game_code) ---")
    model_selection_tbl, cv_full = build_model_selection_cv(agent_games)
    print(model_selection_tbl[["agent", "model", "mean_logloss", "ci_lo", "ci_hi"]]
          .round(3).to_string(index=False))
    make_model_selection_supplement(cv_full)

    # ---- (4) bounded-rationality fingerprint -----------------------------
    fingerprint_tbl = build_fingerprint_table(agent_games)
    print("\n--- f3_fingerprint (used as Figure 3b) ---")
    print(fingerprint_tbl[["agent", "depth_pi", "depth_pi_ci_lo", "depth_pi_ci_hi",
                           "sharpness", "sharpness_ci_lo", "sharpness_ci_hi",
                           "lambda_QLk", "pi_L0", "pi_L1", "pi_L2", "pi_L3"]]
          .round(3).to_string(index=False))

    # ---- (5) figure -------------------------------------------------------
    make_figure(agent_games, lambda_tbl, fingerprint_tbl)

    # ---- honesty NOTE -----------------------------------------------------
    print("\n" + "=" * 78)
    print("HONESTY NOTE")
    print("=" * 78)
    print(
        "  * Ordinal-as-cardinal: rank agents feed ordinal payoffs (1-4) into a logit\n"
        "    utility; delta1c is on that ordinal scale.\n"
        "  * Panel B is a behavioural-model map: quantal level-k depth and decision\n"
        "    sharpness (mean modal-action probability), not a global rationality score.\n"
        "  * Lambda is fit on ONE belief basis q=0.5 for EVERY agent (LLMs + Moore et al.).\n"
        "    Action-space/generated-choice lambda is the headline; soft/policy-space lambda\n"
        "    is calibration/readout robustness. QLk lambda remains in f3_fingerprint.csv\n"
        "    but is not the panel-b y-axis.\n"
        "  * Moore et al. lambda is fit on the individual MGN decisions matched by\n"
        "    perspective; no synthetic human binomial is used.")
    print("\nALL OUTPUTS WRITTEN:")
    for f in ["f3_lambda.csv", "f3_complexity_response.csv", "f3_complexity_bins.csv",
              "f3_complexity_partial.csv", "f3_model_selection_cv.csv",
              "f3_fingerprint.csv"]:
        print(f"  {TAB_DIR / f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
